version: '3'

networks:
  social-network:

services:
  social-setting-nestjs:
    container_name: "Backend"
    image: mettaworldj/social-setting-nestjs
    environment:
      - DATABASE=Database
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "social-setting-mysql"
    ports:
    - 3000:3000
    restart:
      always
    networks:
      - social-network

  social-setting-mysql:
    container_name: "Database"
#    image: library/mysql:5.7.31
#    image: arm64v8/mariadb
    image: mariadb
    environment:
      - MYSQL_DATABASE=social_setting_nestjs
      - MYSQL_ROOT_PASSWORD=Pro2711,.
    ports:
    - 3306:3306
    networks:
      - social-network
